### ISSUE TITLE
Future changes and things you'd change or add.

### ISSUE THREAD

**Issue by ErrorPro** [ErrorPro/react-google-autocomplete#14]
Hi. Here is a list of changes we are going to make eventually. Feel free to comment anything you have in your mind. 

1. Passing a config object as a props to the component(@chexxor). https://github.com/ErrorPro/react-google-autocomplete/issues/12

**Comment by chexxor** [comment]
Thanks for maintaining! That one is still on my to-do list. I've got other, higher priority things right now, though. :(

**Comment by YaAlfred** [comment]
How to change types?(changing property "types", disable the plugin)

**Comment by yamakhalah** [comment]
Adding à value field which can be changed (i mean giving the possibility to manually set the value of the component)

**Comment by wjoeyu** [comment]
I've been trying to implement enter press in the search field to select the first result if there is one, but I have not been able to achieve it.

**Comment by fabrianibrahim** [comment]
@ErrorPro Can we please add debouncing capabilities here?

**Comment by francoro93** [comment]
Not sure if adding the onChange event listener would be feasible? Would help tremendously with manual input and client side form validation

**Comment by rkyslyy** [comment]
Is it possible to add type definitions to avoid adding `declare module 'react-google-autocomplete'` to declaration file in Typescript projects?

**Comment by KoderMAL** [comment]
Debouncing with ms as prop would be great. Can i make a PR for this feature?

**Comment by ErrorPro** [comment]
@KoderMAL Please! Feel free to submit your PR and we can merge it

**Comment by ErrorPro** [comment]
@rkyslyy Added TS annotations on v2 but thinking on rewriting the whole lib with TS later

**Comment by ErrorPro** [comment]
Hey! I just published a new version(v2.1.0) which has a denounce in it. Check it out and let me know your thoughts, thanks

**Comment by nalezhytyi** [comment]
Hey @ErrorPro, It would be super awesome and great if you add 'minChar' prop for <Autocomplete /> component, to reduce the amount of requests.

**Comment by ErrorPro** [comment]
@nalezhytyi Hey! It's already built in the lib and provided by a hook called `usePlacesAutocompleteService` which has debounce in it. Let me know if that's something you are looking for, thanks!

**Comment by pepemaluza** [comment]
How about passing an option in the props which can change what Place type the query returns? So its not fixed as cities

**Comment by sasedlock** [comment]
First off: Thank you for a useful library! 

I am working on an app that requires internationalization. Is it true to say the "Enter a location" language comes via the fact the Google Autocomplete Service is being used? If possible, having a means to pass through this language would be great.

**Comment by p-young** [comment]
Hi @ErrorPro, I'm working on trying to use the sessionToken inside usePlacesAutocompleteService.

I took a quick look at the code and couldn't figure out if it would update the session token at some point, because I believe a fresh session token is needed after each call to placesService.getDetails

It would be helpful to expose a refreshSessionToken() function or something if we need to do that ourselves.

Thanks!

**Comment by ErrorPro** [comment]
I just release v.2.6.0 with an additional method to refresh the session token, check the [readme](https://github.com/ErrorPro/react-google-autocomplete#useplacesautocompleteservice) for more info

**Comment by lassoxo** [comment]
plausible feature?
#154

**Comment by vrinceanuv** [comment]
Adding onChange would be really helpful to type and address that is not found by google.
